LANGUAGES = {
    "af": "afrikaans",
    "sq": "albanian",
    'ar': 'arabic',
    #"an": "aragonese",
    "hy": "armenian",
    "as": "assamese",
    "ay": "aymara",
    "az": "azerbaijani",
    "ba": "bashkir",
    "eu": "basque",
    "be": "belarusian",
    "bn": "bengali",
    "bs": "bosnian",
    "br": "breton",
    'bg': 'bulgarian',
    "ca": "catalan",
    'zh-hans': 'chinese (simplified)',
    'zh-hant': 'chinese (traditional)',
    "hr": "croatian",
    'cs': 'czech',
    'da': 'danish',
    'nl': 'dutch',
    'en-us': 'english',
    "eo": "esperanto",
    'et': 'estonian',
    'fi': 'finnish',
    'fr': 'french',
    "gl": "galician",
    "ka": "georgian",
    'de': 'german',
    'el': 'greek',
    "gn": "guarani",
    "gu": "gujarati",
    "ht": "haitian creole",
    "ha": "hausa",
    "he": "hebrew",
    "hi": "hindi",
    'hu': 'hungarian',
    "is": "icelandic",
    "ig": "igbo",
    'id': 'indonesian',
    "ga": "irish",
    'it': 'italian',
    'ja': 'japanese',
    "jv": "javanese",
    "kk": "kazakh",
    'ko': 'korean',
    "ky": "kyrgyz",
    "la": "latin",
    'lv': 'latvian',
    "ln": "lingala",
    'lt': 'lithuanian',
    "lb": "luxembourgish",
    "mk": "macedonian",
    "mg": "malagasy",
    "ms": "malay",
    "ml": "malayalam",
    "mt": "maltese",
    "mi": "maori",
    "mr": "marathi",
    "mn": "mongolian",
    "my": "myanmar (burmese)",
    "ne": "nepali",
    'nb': 'norwegian',
    "oc": "occitan",
    "om": "oromo",
    "ps": "pashto",
    "fa": "persian",
    'pl': 'polish',
    'pt-pt': 'portuguese',
    'pt-br': 'portuguese (brazil)',
    "pa": "punjabi",
    "qu": "quechua",
    'ro': 'romanian',
    'ru': 'russian',
    "sa": "sanskrit",
    "sr": "serbian",
    "st": "sesotho",
    'sk': 'slovak',
    'sl': 'slovenian',
    'es': 'spanish',
    "su": "sundanese",
    "sw": "swahili",
    'sv': 'swedish',
    #"tl": "tagalog",
    "tg": "tajik",
    "ta": "tamil",
    "tt": "tatar",
    "te": "telugu",
    "th": "thai",
    "ts": "tsonga",
    "tn": "tswana",
    'tr': 'turkish',
    "tk": "turkmen",
    'uk': 'ukrainian',
    "ur": "urdu",
    "uz": "uzbek",
    "vi": "vietnamese",
    "cy": "welsh",
    "wo": "wolof",
    "xh": "xhosa",
    "yi": "yiddish",
    "zu": "zulu"
}

SOURCE_LANGUAGES = {
    "af": "afrikaans",
    "sq": "albanian",
    'ar': 'arabic',
    #"an": "aragonese",
    "hy": "armenian",
    "as": "assamese",
    "ay": "aymara",
    "az": "azerbaijani",
    "ba": "bashkir",
    "eu": "basque",
    "be": "belarusian",
    "bn": "bengali",
    "bs": "bosnian",
    "br": "breton",
    'bg': 'bulgarian',
    "ca": "catalan",
    
    'zh': 'chinese (simplified)',
    'zh': 'chinese (traditional)',
    'zh': 'chinese',
    
    "hr": "croatian",
    'cs': 'czech',
    'da': 'danish',
    'nl': 'dutch',
    'en': 'english',
    "eo": "esperanto",
    'et': 'estonian',
    'fi': 'finnish',
    'fr': 'french',
    "gl": "galician",
    "ka": "georgian",
    'de': 'german',
    'el': 'greek',
    "gn": "guarani",
    "gu": "gujarati",
    "ht": "haitian creole",
    "ha": "hausa",
    "he": "hebrew",
    "hi": "hindi",
    'hu': 'hungarian',
    "is": "icelandic",
    "ig": "igbo",
    'id': 'indonesian',
    "ga": "irish",
    'it': 'italian',
    'ja': 'japanese',
    "jv": "javanese",
    "kk": "kazakh",
    'ko': 'korean',
    "ky": "kyrgyz",
    "la": "latin",
    'lv': 'latvian',
    "ln": "lingala",
    'lt': 'lithuanian',
    "lb": "luxembourgish",
    "mk": "macedonian",
    "mg": "malagasy",
    "ms": "malay",
    "ml": "malayalam",
    "mt": "maltese",
    "mi": "maori",
    "mr": "marathi",
    "mn": "mongolian",
    "my": "myanmar (burmese)",
    "ne": "nepali",
    'nb': 'norwegian',
    "oc": "occitan",
    "om": "oromo",
    "ps": "pashto",
    "fa": "persian",
    'pl': 'polish',
    
    'pt': 'portuguese',
    'pt': 'portuguese (brazil)',
    
    "pa": "punjabi",
    "qu": "quechua",
    'ro': 'romanian',
    'ru': 'russian',
    "sa": "sanskrit",
    "sr": "serbian",
    "st": "sesotho",
    'sk': 'slovak',
    'sl': 'slovenian',
    'es': 'spanish',
    "su": "sundanese",
    "sw": "swahili",
    'sv': 'swedish',
    #"tl": "tagalog",
    "tg": "tajik",
    "ta": "tamil",
    "tt": "tatar",
    "te": "telugu",
    "th": "thai",
    "ts": "tsonga",
    "tn": "tswana",
    'tr': 'turkish',
    "tk": "turkmen",
    'uk': 'ukrainian',
    "ur": "urdu",
    "uz": "uzbek",
    "vi": "vietnamese",
    "cy": "welsh",
    "wo": "wolof",
    "xh": "xhosa",
    "yi": "yiddish",
    "zu": "zulu"
}

LANGKEYS = list(LANGUAGES.keys())
LANGNAMES = list(LANGUAGES.values())
SOURCE_LANGKEYS = list(SOURCE_LANGUAGES.keys())
SOURCE_LANGNAMES = list(SOURCE_LANGUAGES.values())

LANGCODES = dict(map(reversed, LANGUAGES.items()))
SOURCE_LANGCODES = dict(map(reversed, SOURCE_LANGUAGES.items()))